# Generated by Django 5.2 on 2025-04-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(default='000-000-000-00', max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='phone',
            field=models.CharField(default='(00) 0000-0000', max_length=10, verbose_name='Telefone'),
        ),
    ]
