# Generated by Django 5.2 on 2025-04-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usuario_cpf_alter_usuario_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='Joao Souza', max_length=50, unique=True, verbose_name='Nome usuário'),
        ),
    ]
