# Generated by Django 5.2 on 2025-05-14 13:45

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usuario_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='number_home',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='phone',
        ),
        migrations.AddField(
            model_name='usuario',
            name='bairro',
            field=models.CharField(default='Centro', max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='matricula',
            field=models.IntegerField(default='000000', verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='number_address',
            field=models.FloatField(blank=True, max_length=5, null=True, verbose_name='Número enderenço'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_contato',
            field=models.CharField(blank=True, default='(00) 00000-0000', null=True, verbose_name='Número contato'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rg',
            field=models.CharField(default='000-000-000', max_length=10, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(default='Joao Souza', max_length=50, unique=True, verbose_name='Nome usuário'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
