# Generated by Django 5.2 on 2025-05-15 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_usuario_cep_remove_usuario_number_home_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('titulo', models.CharField(unique=True, verbose_name='Título')),
                ('descricao', models.CharField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProtocolo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('titulo', models.CharField(verbose_name='Título')),
                ('descricao', models.CharField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('titulo', models.CharField(unique=True, verbose_name='Título')),
                ('descricao', models.CharField(verbose_name='Descrição')),
            ],
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='address',
            new_name='rua',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='number_address',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cep',
            field=models.CharField(default='00000-000', verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_endereco',
            field=models.FloatField(blank=True, max_length=5, null=True, verbose_name='Número endereço'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.IntegerField(default='000000', unique=True, verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='funcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.funcao'),
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('titulo', models.CharField(unique=True, verbose_name='Título')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('descricao', models.CharField(verbose_name='Descrição')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipoprotocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tipoprotocolo')),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tipousuario'),
        ),
    ]
