# Generated by Django 5.2 on 2025-04-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data da movimentação')),
            ],
        ),
    ]
