# Generated by Django 5.2 on 2025-04-26 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analise', '0001_initial'),
        ('requerimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicomovimentacao',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='requerimentos.processo', verbose_name='Processo'),
        ),
    ]
